# ~/.config/i3/config.d/appearance.conf

# Hide titlebar

new_window pixel

# i3-gaps

# gaps inner 5

# gaps outer 5

# smart_gaps on

default_border pixel 2
hide_edge_borders smart

# Font for window titles

font pango: DejaVu Sans Regular 11

title_align center

# class                 bord. bg. text  ind.  child_border

client.focused          $fg   $bg $fg   $bg   $fg
client.focused_inactive $gray $bg $gray $gray $gray
client.unfocused        $gray $bg $gray $gray $gray
client.urgent           $gray $bg $fg   $gray $gray
client.placeholder      $fg   $bg $fg   $gray $gray

