# ~/.config/i3/config.d/autostart.conf

# Audio
exec --no-startup-id "start-pulseaudio-x11 &"

# Mouse
exec --no-startup-id "/home/salva/scripts/raton.sh"

# Numlock
exec --no-startup-id "numlockx &"

# Startup programs
exec --no-startup-id "sh ~/.config/i3/startup.sh"

# Wallpaper
exec --no-startup-id "nitrogen --set-scaled /home/salva/fondos/darksiders-2-2.jpg"

# Vim background
exec --no-startup-id "~/scripts/setBackgroundVimDark.sh"
