# ~/.config/i3/config.d/bar.conf

# Start i3blocks to display a workspace bar
bar
{
    position top
    workspace_buttons yes
    separator_symbol "|"

    status_command i3blocks

    font pango: DejaVu Sans Regular 13

    colors
    {
        focused_workspace   $fg    $fg    $bg
        active_workspace    $bg    $bg    $white
        inactive_workspace  $bg    $bg    $fg
        urgent_workspace    $bg    $bg    $gray
        background          $bg
    }
}
