# ~/.config/i3/config.d/floating.conf

# Use Mouse+$mod to drag floating windows
floating_modifier $mod

# Enable float for some windows
for_window [class="Variety"] floating enable
for_window [class="Yad"] floating enable

# ChatGPT webapp
for_window [title="ChatGPT"] floating enable
