# ~/.config/i3/config.d/keybinds-system.conf

# Reload config
bindsym $mod+Ctrl+c reload

# Restart i3
bindsym $mod+Ctrl+r restart

# Bar toggle
bindsym $mod+b bar mode toggle

# Power menu
bindsym $mod+Shift+x exec power-menu
bindsym $mod+x exec /home/salva/scripts/dmenuApagar.sh

# Lock screen
bindsym Mod1+Ctrl+l exec --no-startup-id "betterlockscreen -l dim"

# Screenshot
bindsym Print exec --no-startup-id "h-screenshot"

#keymaps
bindsym $mod+F1 exec ~/dotfiles/i3/scripts/show_keys.sh
