# ~/.config/i3/config.d/keybinds-apps.conf

# Terminals
bindsym $mod+Return exec ghostty
bindsym $mod+Shift+Return exec warp-terminal

# Updates
bindsym $mod+Shift+u exec ghostty -e "/home/salva/scripts/actualizar2.sh"

# Browsers
bindsym $mod+g exec google-chrome-stable
bindsym $mod+Shift+g exec firefox

# Filesystem
# bindsym $mod+t exec thunar
bindsym $mod+e exec thunar
# bindsym $mod+Shift+t exec ghostty -e "ranger"
# bindsym $mod+Shift+t exec ghostty -e "yazi"
bindsym $mod+Shift+e exec ghostty -e "yazi"

# AI
# bindsym $mod+Shift+c exec google-chrome-stable --app="https://chatgpt.com"
bindsym $mod+c exec firefox --app="https://chatgpt.com"
bindsym $mod+Shift+c exec code

# Gmail
# bindsym $mod+Shift+c exec google-chrome-stable --app="https://mail.google.com/mail/u/0/#inbox"
bindsym $mod+Shift+w exec firefox --app="https://mail.google.com/mail/u/0/#inbox"

# Editors
bindsym $mod+Shift+s exec subl

# Eclipse
bindsym $mod+Shift+i exec /home/salva/eclipse/java-2021-03/eclipse/eclipse

# Touchpad
bindsym Ctrl+t exec "xinput enable 17"

# Rofi
bindsym $mod+Shift+d exec rofi -modi drun -show drun -theme hash-rofi
bindsym $mod+d exec rofi -modi drun -show drun -theme arthur

# opencode
bindsym $mod+o exec ghostty -e opencode

# pacseek  
bindsym $mod+u exec ghostty -e "pacseek"

# monitors configure
bindsym Ctrl+m exec "~/.screenlayout/defecto\ 3_2_encendidas.sh"
