# ~/.config/i3/config.d/multimedia.conf

# Volume
bindsym XF86AudioRaiseVolume exec "amixer set Master 5%+ unmute && pkill -RTMIN+2 i3blocks"
bindsym XF86AudioLowerVolume exec "amixer set Master 5%- unmute && pkill -RTMIN+2 i3blocks"
bindsym XF86AudioMute exec "amixer -q set Master toggle && pkill -RTMIN+2 i3blocks"
