# ~/.config/i3/config.d/resize.conf

# Resize window mode
mode "resize"
{
    bindsym Left resize shrink width 2 px or 2 ppt
    bindsym Down resize grow height 2 px or 2 ppt
    bindsym Up resize shrink height 2 px or 2 ppt
    bindsym Right resize grow width 2 px or 2 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"
