# ~/.config/i3/config.d/rules.conf

# Always open some programs on specified workspace
assign [class="Mutt"] $workspace2
assign [class="firefox"] $workspace2
assign [class="Google-chrome"] $workspace2
assign [class="Thunderbird"] $workspace2

assign [class="TelegramDesktop"] $workspace3
assign [class="Whatsapp"] $workspace3

assign [class="ranger"] $workspace4
assign [class="Thunar"] $workspace4

assign [class="Code"] $workspace5
assign [class="Subl"] $workspace5

assign [class="VirtualBox"] $workspace8
