# ~/.config/i3/config.d/variables.conf

# Default modkey

set $mod Mod4

# Colors

# set $bg      #0d0d0d
# set $bg      #0B112B
set $bg      #1d2021
set $fg      #83a598
set $cyan    #83a598
set $gray    #928374
set $white   #ebdbb2
# set $white   #ffffff

# Workspace names

set $workspace1 "1  "
set $workspace2 "2  "
set $workspace3 "3  "
set $workspace4 "4  "
set $workspace5 "5  "
set $workspace6 "6  "
set $workspace7 "7  "
set $workspace8 "8  "
set $workspace9 "9  "
set $workspace0 "10  "

