[mgr]
cwd = { fg = "#076678", italic = true }
hovered = { bg = "#ebdbb2" }
preview_hovered = { bg = "#ebdbb2" }
find_keyword = { fg = "#fbf1c7", bg = "#b57614", bold = true }
find_position = { fg = "#427b58", bg = "#d5c4a1", bold = true }
marker_copied = { fg = "#79740e", bg = "#79740e" }
marker_cut = { fg = "#9d0006", bg = "#9d0006" }
marker_marked = { fg = "#8f3f71", bg = "#8f3f71" }
marker_selected = { fg = "#076678", bg = "#076678" }
count_copied = { fg = "#fbf1c7", bg = "#79740e" }
count_cut = { fg = "#fbf1c7", bg = "#9d0006" }
count_selected = { fg = "#fbf1c7", bg = "#076678" }
border_symbol = "│"
border_style = { fg = "#bdae93" }

[tabs]
active = { fg = "#fbf1c7", bg = "#076678" }
inactive = { fg = "#076678", bg = "#ebdbb2" }

[mode]
normal_main = { fg = "#fbf1c7", bg = "#076678", bold = true }
normal_alt = { fg = "#076678", bg = "#ebdbb2" }
select_main = { fg = "#fbf1c7", bg = "#8f3f71", bold = true }
select_alt = { fg = "#8f3f71", bg = "#ebdbb2" }
unset_main = { fg = "#fbf1c7", bg = "#427b58", bold = true }
unset_alt = { fg = "#427b58", bg = "#ebdbb2" }

[status]
overall = { fg = "#3c3836", bg = "#fbf1c7" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
progress_label = { fg = "#3c3836", bold = true }
progress_normal = { fg = "#d5c4a1", bg = "#ebdbb2" }
progress_error = { fg = "#9d0006", bg = "#ebdbb2" }
perm_type = { fg = "#076678" }
perm_read = { fg = "#b57614" }
perm_write = { fg = "#9d0006" }
perm_exec = { fg = "#79740e" }
perm_sep = { fg = "#bdae93" }

[pick]
border = { fg = "#427b58" }
active = { fg = "#3c3836", bg = "#d5c4a1" }
inactive = { fg = "#3c3836" }

[input]
border = { fg = "#427b58" }
title = { fg = "#427b58" }
value = { fg = "#8f3f71" }
selected = { bg = "#d5c4a1" }

[cmp]
border = { fg = "#427b58" }
active = { fg = "#3c3836", bg = "#ebdbb2" }
inactive = { fg = "#3c3836" }
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "#427b58" }
title = { fg = "#427b58" }
hovered = { fg = "#3c3836", bg = "#d5c4a1" }

[which]
cols = 3
mask = { bg = "#fbf1c7" }
cand = { fg = "#427b58" }
rest = { fg = "#076678" }
desc = { fg = "#8f3f71" }
separator = " ➜ "
separator_style = { fg = "#bdae93" }

[confirm]
border = { fg = "#427b58" }
title = { fg = "#427b58" }
content = {}
list = {}
btn_yes = { bg = "#d5c4a1" }
btn_no = {}
btn_labels = ["  [Y]es  ", "  (N)o  "]

[spot]
border = { fg = "#427b58" }
title = { fg = "#427b58" }

[notify]
title_info = { fg = "#427b58" }
title_warn = { fg = "#b57614" }
title_error = { fg = "#9d0006" }
icon_error = ""
icon_warn = ""
icon_info = ""

[help]
on = { fg = "#79740e" }
run = { fg = "#8f3f71" }
desc = { fg = "#427b58" }
hovered = { bg = "#ebdbb2" }
footer = { fg = "#3c3836", bg = "#fbf1c7" }

[filetype]
rules = [
  { mime = "image/*", fg = "#b57614" },
  { mime = "{audio,video}/*", fg = "#8f3f71" },
  { mime = "application/*zip", fg = "#9d0006" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#9d0006" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#427b58" },
  { mime = "*/*", is = "orphan", bg = "#9d0006" },
  { mime = "*/*", is = "exec", fg = "#79740e" },
  { mime = "*/*", name = "*/", fg = "#076678" },
  { mime = "*/*", fg = "#3c3836" },
]
